// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto_Dotnet8.Data;

#nullable disable

namespace Projeto_Dotnet8.Migrations
{
    [DbContext(typeof(BancoContext))]
    [Migration("20251003011402_greg")]
    partial class greg
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Projeto_Dotnet8.Models.ComputadorModels", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DataPostagem")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SalaModelsID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SalaModelsID");

                    b.ToTable("Computadores");
                });

            modelBuilder.Entity("Projeto_Dotnet8.Models.MensagemModels", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ComputadorID")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("ComputadorID");

                    b.ToTable("Mensagens");
                });

            modelBuilder.Entity("Projeto_Dotnet8.Models.SalaModels", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Sala_Num")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Salas");
                });

            modelBuilder.Entity("Projeto_Dotnet8.Models.ComputadorModels", b =>
                {
                    b.HasOne("Projeto_Dotnet8.Models.SalaModels", null)
                        .WithMany("Computadores")
                        .HasForeignKey("SalaModelsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Projeto_Dotnet8.Models.MensagemModels", b =>
                {
                    b.HasOne("Projeto_Dotnet8.Models.ComputadorModels", "Computador")
                        .WithMany("Mensagens")
                        .HasForeignKey("ComputadorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Computador");
                });

            modelBuilder.Entity("Projeto_Dotnet8.Models.ComputadorModels", b =>
                {
                    b.Navigation("Mensagens");
                });

            modelBuilder.Entity("Projeto_Dotnet8.Models.SalaModels", b =>
                {
                    b.Navigation("Computadores");
                });
#pragma warning restore 612, 618
        }
    }
}
